stud1 = {"marital_status": "Single",
         "application_mode": "Over 23 years old",
         "application_order": 1,
         "course": "Nursing",
         "daytime_or_evening_attendance": "daytime",
         "previous_qualification": "Secondary education",
         "mother_qualification": "General Course of Administration and Commerce",
         "father_qualification": "Basic Education 3rd Cycle (9th/10th/11th Year) or Equivalent",
         "mother_occupation": "Unskilled Workers",
         "father_occupation": "Installation and Machine Operators and Assembly Workers",
         "displaced": "yes",
         "debtor": "no",
         "tuition_fees_up_to_date": "yes",
         "gender": "female",
         "scholarship_holder": "no",
         "age": 27,
         "curricular_units_1st_sem_(credited)": 0,
         "curricular_units_1st_sem_(enrolled)": 7,
         "curricular_units_1st_sem_(evaluations)": 14,
         "curricular_units_1st_sem_(approved)": 0,
         "curricular_units_1st_sem_(grade)": 0.0,
         "curricular_units_1st_sem_(without_evaluations)": 0,
         "curricular_units_2nd_sem_(credited)": 0,
         "curricular_units_2nd_sem_(enrolled)": 7,
         "curricular_units_2nd_sem_(evaluations)": 14,
         "curricular_units_2nd_sem_(approved)": 0,
         "curricular_units_2nd_sem_(grade)": 0.0,
         "curricular_units_2nd_sem_(without_evaluations)": 0,
         "inflation_rate": 0.6,
         "gdp": 2.02}
stud1_dropout = 1

stud2 = {"marital_status": "Single",
         "application_mode": "Technological specialization diploma holders",
         "application_order": 1,
         "course": "Agronomy",
         "daytime_or_evening_attendance": "daytime",
         "previous_qualification": "Technological specialization course",
         "mother_qualification": "Supplementary Accounting and Administration",
         "father_qualification": "Basic Education 2nd Cycle (6th/7th/8th Year) or equivalent",
         "mother_occupation": "Farmers and Skilled Workers in Agriculture, Fisheries, and Forestry",
         "father_occupation": "Farmers and Skilled Workers in Agriculture, Fisheries, and Forestry",
         "displaced": "yes",
         "debtor": "no",
         "tuition_fees_up_to_date": "yes",
         "gender": "female",
         "scholarship_holder": "no",
         "age": 21,
         "curricular_units_1st_sem_(credited)": 0,
         "curricular_units_1st_sem_(enrolled)": 6,
         "curricular_units_1st_sem_(evaluations)": 11,
         "curricular_units_1st_sem_(approved)": 6,
         "curricular_units_1st_sem_(grade)": 13.428571428571429,
         "curricular_units_1st_sem_(without_evaluations)": 0,
         "curricular_units_2nd_sem_(credited)": 0,
         "curricular_units_2nd_sem_(enrolled)": 6,
         "curricular_units_2nd_sem_(evaluations)": 12,
         "curricular_units_2nd_sem_(approved)": 6,
         "curricular_units_2nd_sem_(grade)": 12.857142857142858,
         "curricular_units_2nd_sem_(without_evaluations)": 0,
         "inflation_rate": 2.8,
         "gdp": -4.06}
stud2_dropout = 0

stud3 = {"marital_status": "Single",
         "application_mode": "1st phase-general contingent",
         "application_order": 1,
         "course": "Informatics Engineering",
         "daytime_or_evening_attendance": "daytime",
         "previous_qualification": "Secondary education",
         "mother_qualification": "Higher Education-degree",
         "father_qualification": "Secondary Education-12th Year of Schooling or Equivalent",
         "mother_occupation": "Specialists in Intellectual and Scientific Activities",
         "father_occupation": "Intermediate Level Technicians and Professions",
         "displaced": "no",
         "debtor": "no",
         "tuition_fees_up_to_date": "yes",
         "gender": "male",
         "scholarship_holder": "no",
         "age": 20,
         "curricular_units_1st_sem_(credited)": 0,
         "curricular_units_1st_sem_(enrolled)": 5,
         "curricular_units_1st_sem_(evaluations)": 9,
         "curricular_units_1st_sem_(approved)": 4,
         "curricular_units_1st_sem_(grade)": 11.6,
         "curricular_units_1st_sem_(without_evaluations)": 0,
         "curricular_units_2nd_sem_(credited)": 0,
         "curricular_units_2nd_sem_(enrolled)": 5,
         "curricular_units_2nd_sem_(evaluations)": 7,
         "curricular_units_2nd_sem_(approved)": 4,
         "curricular_units_2nd_sem_(grade)": 12.25,
         "curricular_units_2nd_sem_(without_evaluations)": 2,
         "inflation_rate": 2.6,
         "gdp": 0.32}

stud3_dropout = 0

stud4 = {"marital_status": "Single",
         "application_mode": "Holders of other higher courses",
         "application_order": 1,
         "course": "Nursing",
         "daytime_or_evening_attendance": "daytime",
         "previous_qualification": "Higher education-degree",
         "mother_qualification": "Secondary Education-12th Year of Schooling or Equivalent",
         "father_qualification": "Secondary Education-12th Year of Schooling or Equivalent",
         "mother_occupation": "Unskilled Workers",
         "father_occupation": "Personal Services, Security and Safety Workers, and Sellers",
         "displaced": "no",
         "debtor": "no",
         "tuition_fees_up_to_date": "yes",
         "gender": "female",
         "scholarship_holder": "no",
         "age": 33,
         "curricular_units_1st_sem_(credited)": 2,
         "curricular_units_1st_sem_(enrolled)": 7,
         "curricular_units_1st_sem_(evaluations)": 8,
         "curricular_units_1st_sem_(approved)": 6,
         "curricular_units_1st_sem_(grade)": 14.35,
         "curricular_units_1st_sem_(without_evaluations)": 0,
         "curricular_units_2nd_sem_(credited)": 3,
         "curricular_units_2nd_sem_(enrolled)": 8,
         "curricular_units_2nd_sem_(evaluations)": 10,
         "curricular_units_2nd_sem_(approved)": 6,
         "curricular_units_2nd_sem_(grade)": 14.583333333333334,
         "curricular_units_2nd_sem_(without_evaluations)": 0,
         "inflation_rate": 0.3,
         "gdp": -0.92}

stud4_dropout = 1

stud5 = {"marital_status": "Single",
 "application_mode": "1st phase-general contingent",
 "application_order": 6,
 "course": "Animation and Multimedia Design",
 "daytime_or_evening_attendance": "daytime",
 "previous_qualification": "Secondary education",
 "mother_qualification": "General commerce course",
 "father_qualification": "Basic education 1st cycle (4th/5th year) or equivalent",
 "mother_occupation": "Personal Services, Security and Safety Workers, and Sellers",
 "father_occupation": "Personal Services, Security and Safety Workers, and Sellers",
 "displaced": "yes",
 "debtor": "no",
 "tuition_fees_up_to_date": "yes",
 "gender": "female",
 "scholarship_holder": "yes",
 "age": 18,
 "curricular_units_1st_sem_(credited)": 0,
 "curricular_units_1st_sem_(enrolled)": 0,
 "curricular_units_1st_sem_(evaluations)": 0,
 "curricular_units_1st_sem_(approved)": 0,
 "curricular_units_1st_sem_(grade)": 0.0,
 "curricular_units_1st_sem_(without_evaluations)": 0,
 "curricular_units_2nd_sem_(credited)": 0,
 "curricular_units_2nd_sem_(enrolled)": 0,
 "curricular_units_2nd_sem_(evaluations)": 0,
 "curricular_units_2nd_sem_(approved)": 0,
 "curricular_units_2nd_sem_(grade)": 0.0,
 "curricular_units_2nd_sem_(without_evaluations)": 0,
 "inflation_rate": -0.8,
 "gdp": -3.12}

stud5_dropout = 0


stud6={"marital_status": "Single",
 "application_mode": "2nd phase-general contingent",
 "application_order": 2,
 "course": "Journalism and Communication",
 "daytime_or_evening_attendance": "daytime",
 "previous_qualification": "Secondary education",
 "mother_qualification": "Secondary Education-12th Year of Schooling or Equivalent",
 "father_qualification": "Secondary Education-12th Year of Schooling or Equivalent",
 "mother_occupation": "Intermediate Level Technicians and Professions",
 "father_occupation": "Intermediate Level Technicians and Professions",
 "displaced": "yes",
 "debtor": "no",
 "tuition_fees_up_to_date": "yes",
 "gender": "female",
 "scholarship_holder": "no",
 "age": 18,
 "curricular_units_1st_sem_(credited)": 0,
 "curricular_units_1st_sem_(enrolled)": 6,
 "curricular_units_1st_sem_(evaluations)": 0,
 "curricular_units_1st_sem_(approved)": 0,
 "curricular_units_1st_sem_(grade)": 0.0,
 "curricular_units_1st_sem_(without_evaluations)": 0,
 "curricular_units_2nd_sem_(credited)": 0,
 "curricular_units_2nd_sem_(enrolled)": 6,
 "curricular_units_2nd_sem_(evaluations)": 0,
 "curricular_units_2nd_sem_(approved)": 0,
 "curricular_units_2nd_sem_(grade)": 0.0,
 "curricular_units_2nd_sem_(without_evaluations)": 0,
 "inflation_rate": -0.3,
 "gdp": 0.79}

stud6_dropout = 1
